# Generated by Django 3.1.3 on 2021-02-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210225_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['post_date']},
        ),
    ]
